#!/usr/bin/env bash
# src/commands/config.sh - Manage configuration
# Usage: workflow config [options]

set -euo pipefail

# Source libraries
: "${LIB_DIR:=$(cd "$(dirname "${BASH_SOURCE[0]}")/../lib" && pwd)}"
# shellcheck source=src/lib/common.sh
source "${LIB_DIR}/common.sh"
# shellcheck source=src/lib/config.sh
source "${LIB_DIR}/config.sh"
# shellcheck source=src/lib/provider.sh
source "${LIB_DIR}/provider.sh"

# cmd_config() - Main config command handler
cmd_config() {
    local edit=false
    local get_key=""
    local set_pair=""
    local set_model=""
    local set_provider=""
    local list_all=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --edit)
                edit=true
                shift
                ;; 
            --get)
                if [[ -z "${2:-}" ]]; then
                    die "Option --get requires an argument"
                fi
                get_key="$2"
                shift 2
                ;; 
            --set)
                if [[ -z "${2:-}" ]]; then
                    die "Option --set requires an argument (format: key=value)"
                fi
                set_pair="$2"
                shift 2
                ;; 
            --set-model)
                if [[ -z "${2:-}" ]]; then
                    die "Option --set-model requires an argument"
                fi
                set_model="$2"
                shift 2
                ;; 
            --set-provider)
                if [[ -z "${2:-}" ]]; then
                    die "Option --set-provider requires an argument"
                fi
                set_provider="$2"
                shift 2
                ;; 
            --list|--all)
                list_all=true
                shift
                ;; 
            --help|-h)
                show_help
                exit 0
                ;; 
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;; 
        esac
    done

    log_debug "Starting config command"

    # Get config file path
    local config_file
    config_file=$(get_config_file_path)

    # Ensure config file exists
    if [[ ! -f "$config_file" ]]; then
        log_warn "Configuration file not found: $config_file"
        log_info "Creating default configuration file..."
        create_default_config "$config_file"
    fi

    # Execute appropriate action
    if [[ "$edit" == "true" ]]; then
        edit_config "$config_file"
    elif [[ -n "$set_model" ]]; then
        configure_single_model "$config_file" "$set_model"
    elif [[ -n "$set_provider" ]]; then
        configure_provider_defaults "$config_file" "$set_provider"
    elif [[ -n "$get_key" ]]; then
        get_config_value "$get_key"
    elif [[ -n "$set_pair" ]]; then
        set_config_value "$config_file" "$set_pair"
    elif [[ "$list_all" == "true" ]]; then
        show_full_config "$config_file"
    else
        show_config_summary "$config_file"
    fi

    return 0
}

# get_config_file_path() - Get the config file path
get_config_file_path() {
    local config_file="${WORKFLOW_CONFIG:-}"
    local git_root

    # Determine config file location
    if [[ -z "$config_file" ]]; then
        if git_root="$(get_git_root 2>/dev/null)"; then
            config_file="${git_root}/.workflow/config.sh"
        else
            config_file=".workflow/config.sh"
        fi
    fi

    echo "$config_file"
}

# create_default_config() - Create default configuration file
create_default_config() {
    local config_file="$1"

    # Ensure directory exists
    local config_dir
    config_dir="$(dirname "$config_file")"
    ensure_dir "$config_dir" || die "Failed to create config directory: $config_dir"

    # Write default configuration
    cat > "$config_file" <<'EOF'
# Spec-to-Ship Workflow Configuration
# Generated by workflow config

# Provider Selection (claude, opencode, openai)
PROVIDER_DEFAULT="claude"
# PROVIDER_CLARIFY="claude"
# PROVIDER_SPECS="claude"
# PROVIDER_ARCH="claude"
# PROVIDER_PLAN="claude"
# PROVIDER_BUILD="claude"
# PROVIDER_GATE="claude"
# PROVIDER_FEEDBACK="claude"

# Provider-Specific Model Mappings
# Claude Models
PROVIDER_CLAUDE_MODEL_HIGH="claude-opus-4-20250514"
PROVIDER_CLAUDE_MODEL_MEDIUM="claude-sonnet-4-5-20250929"
PROVIDER_CLAUDE_MODEL_LOW="claude-haiku-4-20250319"

# OpenCode Models
PROVIDER_OPENCODE_MODEL_HIGH="opencode/grok-code"
PROVIDER_OPENCODE_MODEL_MEDIUM="opencode/gpt-5-nano"
PROVIDER_OPENCODE_MODEL_LOW="opencode/glm-4.7-free"

# Capability Requirements per Phase (high, medium, low)
# CAPABILITY_CLARIFY="high"
# CAPABILITY_SPECS="medium"
# CAPABILITY_ARCH="high"
# CAPABILITY_PLAN="high"
# CAPABILITY_BUILD="high"
# CAPABILITY_GATE="medium"
# CAPABILITY_FEEDBACK="low"

# Legacy Model Selection (backward compatibility)
MODEL_CLARIFY="opus"
MODEL_SPECS="sonnet"
MODEL_ARCH="opus"
MODEL_PLAN="opus"
MODEL_BUILD_PRIMARY="opus"
MODEL_BUILD_SECONDARY="sonnet"
MODEL_GATE="sonnet"
MODEL_FEEDBACK="haiku"

# Human-in-the-Loop (HITL) Settings
HITL_ENABLED="false"
HITL_MODE="milestone"  # task, milestone, uncertain, every:N
HITL_TIMEOUT=""        # e.g., "5m", "1h" (empty for no timeout)

# Build Settings
BUILD_MAX_ITERATIONS="0"            # 0 = unlimited
BUILD_BACKPRESSURE_TESTS="true"     # Run tests before commit
BUILD_BACKPRESSURE_TYPECHECK="false" # Run typecheck before commit
BUILD_BACKPRESSURE_LINT="true"      # Run lint before commit

# Retry Settings
RETRY_MAX_ATTEMPTS="3"
RETRY_BASE_DELAY="2"

# Notes:
# - Provider selection allows mixing different AI providers per phase
# - Capabilities map to provider-specific models automatically
# - Legacy model settings still work for backward compatibility
# - Secrets should be stored in environment variables (e.g., CLAUDE_API_KEY)
# - Use WORKFLOW_<KEY> environment variables to override these settings
# - Edit with: workflow config --edit
EOF

    log_info "Created default configuration: $config_file"
}

# edit_config() - Open config file in editor
edit_config() {
    local config_file="$1"

    local editor="${EDITOR:-nano}"

    log_info "Opening config in editor: $editor"

    # Check if editor exists
    if ! command -v "$editor" >/dev/null 2>&1; then
        die "Editor not found: $editor (set EDITOR environment variable)"
    fi

    # Open editor
    "$editor" "$config_file"

    log_info "Configuration updated: $config_file"
    return 0
}

# get_config_value() - Get specific config value
get_config_value() {
    local key="$1"

    # Load configuration
    config_load

    # Get value directly from CONFIG array
    if [[ -v CONFIG[$key] ]] && [[ -n "${CONFIG[$key]:-}" ]]; then
        # Value exists and is non-empty
        printf '%s\n' "${CONFIG[$key]}"
        return 0
    elif [[ -v CONFIG[$key] ]]; then
        # Value exists but is empty (like HITL_TIMEOUT)
        printf '%s\n' "${CONFIG[$key]}"
        return 0
    else
        log_error "Configuration key not found: $key"
        return 1
    fi
}

# set_config_value_internal() - Helper to set value in file without logging/validation (for batch updates)
set_config_value_internal() {
    local config_file="$1"
    local key="$2"
    local value="$3"

    # Update config file using awk to avoid sed escaping issues
    if grep -q "^${key}=" "$config_file" 2>/dev/null; then
        # Key exists, update it using awk
        local temp_file="${config_file}.tmp"
        awk -v key="$key" -v value="$value" '
            BEGIN { updated=0 }
            $0 ~ "^" key "=" { print key "=\"" value "\""; updated=1; next }
            { print }
        ' "$config_file" > "$temp_file"

        if ! mv "$temp_file" "$config_file"; then
            rm -f "$temp_file"
            return 1
        fi
    else
        # Key doesn't exist, append it
        echo "${key}=\"${value}\"" >> "$config_file"
    fi
    return 0
}

# remove_config_value_internal() - Helper to remove value from file
remove_config_value_internal() {
    local config_file="$1"
    local key="$2"

    if grep -q "^${key}=" "$config_file" 2>/dev/null; then
        local temp_file="${config_file}.tmp"
        awk -v key="$key" '
            $0 !~ "^" key "=" { print }
        ' "$config_file" > "$temp_file"

        if ! mv "$temp_file" "$config_file"; then
            rm -f "$temp_file"
            return 1
        fi
    fi
    return 0
}

# set_config_value() - Set config value and persist to file (public API)
set_config_value() {
    local config_file="$1"
    local set_pair="$2"

    # Parse key=value
    if [[ ! "$set_pair" =~ ^([^=]+)=(.*)$ ]]; then
        die "Invalid format for --set. Expected: key=value"
    fi

    local key="${BASH_REMATCH[1]}"
    local value="${BASH_REMATCH[2]}"

    # Validate key exists in defaults
    config_load
    if ! config_set "$key" "$value"; then
        die "Invalid configuration key: $key"
    fi

    log_debug "Setting config: $key=$value"

    if set_config_value_internal "$config_file" "$key" "$value"; then
        log_info "Updated configuration: $key=$value"
    else
        die "Failed to update configuration file: $config_file"
    fi

    return 0
}

# configure_single_model() - Set one model for everything
configure_single_model() {
    local config_file="$1"
    local model="$2"

    log_info "Configuring workflow to use '$model' for everything..."

    # Detect provider
    local provider
    provider="$(provider_detect_from_model "$model")"
    log_info "Detected provider: $provider"

    # Load current config to validate
    config_load

    # Set Default Provider
    set_config_value_internal "$config_file" "PROVIDER_DEFAULT" "$provider"

    # Set High/Medium/Low models for this provider
    set_config_value_internal "$config_file" "PROVIDER_${provider^^}_MODEL_HIGH" "$model"
    set_config_value_internal "$config_file" "PROVIDER_${provider^^}_MODEL_MEDIUM" "$model"
    set_config_value_internal "$config_file" "PROVIDER_${provider^^}_MODEL_LOW" "$model"

    # Remove phase-specific provider overrides to ensure default is used
    local phases=(CLARIFY SPECS ARCH PLAN BUILD GATE FEEDBACK)
    for phase in "${phases[@]}"; do
        remove_config_value_internal "$config_file" "PROVIDER_${phase}"
    done

    log_info "✓ Configuration updated: All phases will use '$model' (Provider: $provider)"
    echo ""
    echo "Summary:"
    echo "- Default Provider: $provider"
    echo "- Models (High/Med/Low): $model"
    echo "- Phase Overrides: Cleared"
}

# configure_provider_defaults() - Switch provider with its default models
configure_provider_defaults() {
    local config_file="$1"
    local provider="$2"

    log_info "Switching default provider to '$provider'..."

    # Load defaults to get standard models if available
    # We can't easily reset to "factory defaults" for specific keys without hardcoding them here
    # or reading them from src/lib/config.sh which is already sourced.
    
    # Check if provider is valid
    if ! _is_valid_provider "$provider"; then
         log_warn "Provider '$provider' is not in the standard list (${VALID_PROVIDERS[*]}). Proceeding anyway."
    fi

    # Set Default Provider
    set_config_value_internal "$config_file" "PROVIDER_DEFAULT" "$provider"

    # Remove phase-specific provider overrides
    local phases=(CLARIFY SPECS ARCH PLAN BUILD GATE FEEDBACK)
    for phase in "${phases[@]}"; do
        remove_config_value_internal "$config_file" "PROVIDER_${phase}"
    done

    log_info "✓ Configuration updated: Default provider set to '$provider'"
    log_info "Note: Model mappings for $provider were left as-is (or defaults)."
}

# show_config_summary() - Display simplified configuration summary
show_config_summary() {
    local config_file="$1"

    # Load configuration
    config_load

    echo "Configuration Summary ($config_file)"
    echo "================================================================================"

    local default_provider
    default_provider="$(config_get "PROVIDER_DEFAULT")"
    echo "Default Provider: ${COLOR_CYAN}${default_provider}${COLOR_RESET}"
    
    # Show models for default provider
    local high med low
    high="$(config_get "PROVIDER_${default_provider^^}_MODEL_HIGH" || echo "N/A")"
    med="$(config_get "PROVIDER_${default_provider^^}_MODEL_MEDIUM" || echo "N/A")"
    low="$(config_get "PROVIDER_${default_provider^^}_MODEL_LOW" || echo "N/A")"

    echo "Default Models:"
    echo "  High Capability:   $high"
    echo "  Medium Capability: $med"
    echo "  Low Capability:    $low"
    echo ""

    # Show Phase Overrides
    echo "Phase Overrides:"
    local phases=(CLARIFY SPECS ARCH PLAN BUILD GATE FEEDBACK)
    local has_overrides=false

    for phase in "${phases[@]}"; do
        local phase_provider
        phase_provider="$(config_get "PROVIDER_${phase}" || echo "")"
        
        if [[ -n "$phase_provider" && "$phase_provider" != "$default_provider" ]]; then
            echo "  - ${phase}: Uses provider ${COLOR_CYAN}${phase_provider}${COLOR_RESET}"
            has_overrides=true
        fi
    done

    if [[ "$has_overrides" == "false" ]]; then
        echo "  (None - all phases use default provider)"
    fi

    echo ""
    echo "Tips:"
    echo "  Use '--set-model <model>' to use one model for everything."
    echo "  Use '--set-provider <provider>' to switch default provider."
    echo "  Use '--list' to see all configuration options (including HITL, Build, etc)."
}

# show_full_config() - Display full configuration (Legacy + New)
show_full_config() {
    local config_file="$1"

    log_debug "Showing full configuration"

    # Load configuration
    config_load

    echo "Configuration file: $config_file"
    echo ""

    echo "=== Provider Settings ==="
    echo "PROVIDER_DEFAULT=$(config_get PROVIDER_DEFAULT)"
    for p in CLARIFY SPECS ARCH PLAN BUILD GATE FEEDBACK; do
        val="$(config_get "PROVIDER_$p" || echo "")"
        [[ -n "$val" ]] && echo "PROVIDER_$p=$val"
    done
    echo ""

    echo "=== Model Mappings ==="
    # Show mapping for active providers
    for prov in CLAUDE OPENCODE OPENAI GEMINI; do
        h="$(config_get "PROVIDER_${prov}_MODEL_HIGH" || echo "")"
        if [[ -n "$h" ]]; then
            echo "PROVIDER_${prov}_MODEL_HIGH=$h"
            echo "PROVIDER_${prov}_MODEL_MEDIUM=$(config_get "PROVIDER_${prov}_MODEL_MEDIUM")"
            echo "PROVIDER_${prov}_MODEL_LOW=$(config_get "PROVIDER_${prov}_MODEL_LOW")"
        fi
    done
    echo ""

    echo "=== HITL Settings ==="
    echo "HITL_ENABLED=$(config_get HITL_ENABLED)"
    echo "HITL_MODE=$(config_get HITL_MODE)"
    echo "HITL_TIMEOUT=$(config_get HITL_TIMEOUT || echo '(none)')"
    echo ""

    echo "=== Build Settings ==="
    echo "BUILD_MAX_ITERATIONS=$(config_get BUILD_MAX_ITERATIONS)"
    echo "BUILD_BACKPRESSURE_TESTS=$(config_get BUILD_BACKPRESSURE_TESTS)"
    echo "BUILD_BACKPRESSURE_TYPECHECK=$(config_get BUILD_BACKPRESSURE_TYPECHECK)"
    echo "BUILD_BACKPRESSURE_LINT=$(config_get BUILD_BACKPRESSURE_LINT)"
    echo ""

    echo "=== Legacy/Compat Settings ==="
    echo "MODEL_CLARIFY=$(config_get MODEL_CLARIFY)"
    echo "MODEL_SPECS=$(config_get MODEL_SPECS)"
    # ... other legacy models ...
    
    return 0
}

# show_help() - Display help message
show_help() {
    cat <<EOF
workflow config - Manage configuration

USAGE:
    workflow config [options]

DESCRIPTION:
    Manage workflow configuration settings.

OPTIONS:
    --set-model MODEL   Set a single model to be used for ALL phases (Simplest UX)
    --set-provider PROV Set the default provider (e.g., claude, opencode)
    --list, --all       Show full configuration details
    --edit              Open config file in \$EDITOR
    --get KEY           Get specific config value
    --set KEY=VALUE     Set config value (persists to file)
    --help, -h          Show this help message

EXAMPLES:
    # Show summary
    workflow config

    # Use Claude 3 Opus for everything
    workflow config --set-model claude-3-opus-20240229

    # Use OpenCode provider for everything (with default models)
    workflow config --set-provider opencode

    # Show all configuration details
    workflow config --list

    # Enable HITL
    workflow config --set HITL_ENABLED=true

EXIT CODES:
    0    Success
    1    Error
EOF
}

# Main execution
main() {
    cmd_config "$@"
}

# Run main if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi