#!/usr/bin/env bash
# src/commands/config.sh - Manage configuration
# Usage: workflow config [options]

set -euo pipefail

# Source libraries
: "${LIB_DIR:=$(cd "$(dirname "${BASH_SOURCE[0]}")/../lib" && pwd)}"
# shellcheck source=src/lib/common.sh
source "${LIB_DIR}/common.sh"
# shellcheck source=src/lib/config.sh
source "${LIB_DIR}/config.sh"

# cmd_config() - Main config command handler
cmd_config() {
    local edit=false
    local get_key=""
    local set_pair=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --edit)
                edit=true
                shift
                ;;
            --get)
                if [[ -z "${2:-}" ]]; then
                    die "Option --get requires an argument"
                fi
                get_key="$2"
                shift 2
                ;;
            --set)
                if [[ -z "${2:-}" ]]; then
                    die "Option --set requires an argument (format: key=value)"
                fi
                set_pair="$2"
                shift 2
                ;;
            --help|-h)
                show_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done

    log_debug "Starting config command"

    # Get config file path
    local config_file
    config_file=$(get_config_file_path)

    # Ensure config file exists
    if [[ ! -f "$config_file" ]]; then
        log_warn "Configuration file not found: $config_file"
        log_info "Creating default configuration file..."
        create_default_config "$config_file"
    fi

    # Execute appropriate action
    if [[ "$edit" == "true" ]]; then
        edit_config "$config_file"
    elif [[ -n "$get_key" ]]; then
        get_config_value "$get_key"
    elif [[ -n "$set_pair" ]]; then
        set_config_value "$config_file" "$set_pair"
    else
        # No options: show full config
        show_full_config "$config_file"
    fi

    return 0
}

# get_config_file_path() - Get the config file path
get_config_file_path() {
    local config_file="${WORKFLOW_CONFIG:-}"
    local git_root

    # Determine config file location
    if [[ -z "$config_file" ]]; then
        if git_root="$(get_git_root 2>/dev/null)"; then
            config_file="${git_root}/.workflow/config.sh"
        else
            config_file=".workflow/config.sh"
        fi
    fi

    echo "$config_file"
}

# create_default_config() - Create default configuration file
create_default_config() {
    local config_file="$1"

    # Ensure directory exists
    local config_dir
    config_dir="$(dirname "$config_file")"
    ensure_dir "$config_dir" || die "Failed to create config directory: $config_dir"

    # Write default configuration
    cat > "$config_file" <<'EOF'
# Spec-to-Ship Workflow Configuration
# Generated by workflow config

# Provider Selection (claude, opencode, openai)
PROVIDER_DEFAULT="claude"
# PROVIDER_CLARIFY="claude"
# PROVIDER_SPECS="claude"
# PROVIDER_ARCH="claude"
# PROVIDER_PLAN="claude"
# PROVIDER_BUILD="claude"
# PROVIDER_GATE="claude"
# PROVIDER_FEEDBACK="claude"

# Provider-Specific Model Mappings
# Claude Models
PROVIDER_CLAUDE_MODEL_HIGH="claude-opus-4-20250514"
PROVIDER_CLAUDE_MODEL_MEDIUM="claude-sonnet-4-5-20250929"
PROVIDER_CLAUDE_MODEL_LOW="claude-haiku-4-20250319"

# OpenCode Models
PROVIDER_OPENCODE_MODEL_HIGH="opencode/grok-code"
PROVIDER_OPENCODE_MODEL_MEDIUM="opencode/gpt-5-nano"
PROVIDER_OPENCODE_MODEL_LOW="opencode/glm-4.7-free"

# Capability Requirements per Phase (high, medium, low)
# CAPABILITY_CLARIFY="high"
# CAPABILITY_SPECS="medium"
# CAPABILITY_ARCH="high"
# CAPABILITY_PLAN="high"
# CAPABILITY_BUILD="high"
# CAPABILITY_GATE="medium"
# CAPABILITY_FEEDBACK="low"

# Legacy Model Selection (backward compatibility)
MODEL_CLARIFY="opus"
MODEL_SPECS="sonnet"
MODEL_ARCH="opus"
MODEL_PLAN="opus"
MODEL_BUILD_PRIMARY="opus"
MODEL_BUILD_SECONDARY="sonnet"
MODEL_GATE="sonnet"
MODEL_FEEDBACK="haiku"

# Human-in-the-Loop (HITL) Settings
HITL_ENABLED="false"
HITL_MODE="milestone"  # task, milestone, uncertain, every:N
HITL_TIMEOUT=""        # e.g., "5m", "1h" (empty for no timeout)

# Build Settings
BUILD_MAX_ITERATIONS="0"            # 0 = unlimited
BUILD_BACKPRESSURE_TESTS="true"     # Run tests before commit
BUILD_BACKPRESSURE_TYPECHECK="false" # Run typecheck before commit
BUILD_BACKPRESSURE_LINT="true"      # Run lint before commit

# Retry Settings
RETRY_MAX_ATTEMPTS="3"
RETRY_BASE_DELAY="2"

# Notes:
# - Provider selection allows mixing different AI providers per phase
# - Capabilities map to provider-specific models automatically
# - Legacy model settings still work for backward compatibility
# - Secrets should be stored in environment variables (e.g., CLAUDE_API_KEY)
# - Use WORKFLOW_<KEY> environment variables to override these settings
# - Edit with: workflow config --edit
EOF

    log_info "Created default configuration: $config_file"
}

# edit_config() - Open config file in editor
edit_config() {
    local config_file="$1"

    local editor="${EDITOR:-nano}"

    log_info "Opening config in editor: $editor"

    # Check if editor exists
    if ! command -v "$editor" >/dev/null 2>&1; then
        die "Editor not found: $editor (set EDITOR environment variable)"
    fi

    # Open editor
    "$editor" "$config_file"

    log_info "Configuration updated: $config_file"
    return 0
}

# get_config_value() - Get specific config value
get_config_value() {
    local key="$1"

    # Load configuration
    config_load

    # Get value directly from CONFIG array
    if [[ -v CONFIG[$key] ]] && [[ -n "${CONFIG[$key]:-}" ]]; then
        # Value exists and is non-empty
        printf '%s\n' "${CONFIG[$key]}"
        return 0
    elif [[ -v CONFIG[$key] ]]; then
        # Value exists but is empty (like HITL_TIMEOUT)
        printf '%s\n' "${CONFIG[$key]}"
        return 0
    else
        log_error "Configuration key not found: $key"
        return 1
    fi
}

# set_config_value() - Set config value and persist to file
set_config_value() {
    local config_file="$1"
    local set_pair="$2"

    # Parse key=value
    if [[ ! "$set_pair" =~ ^([^=]+)=(.*)$ ]]; then
        die "Invalid format for --set. Expected: key=value"
    fi

    local key="${BASH_REMATCH[1]}"
    local value="${BASH_REMATCH[2]}"

    # Validate key exists in defaults
    config_load
    if ! config_set "$key" "$value"; then
        die "Invalid configuration key: $key"
    fi

    log_debug "Setting config: $key=$value"

    # Update config file using awk to avoid sed escaping issues
    if grep -q "^${key}=" "$config_file" 2>/dev/null; then
        # Key exists, update it using awk
        local temp_file="${config_file}.tmp"
        awk -v key="$key" -v value="$value" '
            BEGIN { updated=0 }
            $0 ~ "^" key "=" { print key "=\"" value "\""; updated=1; next }
            { print }
        ' "$config_file" > "$temp_file"

        if mv "$temp_file" "$config_file"; then
            log_info "Updated configuration: $key=$value"
        else
            rm -f "$temp_file"
            die "Failed to update configuration file: $config_file"
        fi
    else
        # Key doesn't exist, append it
        echo "${key}=\"${value}\"" >> "$config_file"
        log_info "Added configuration: $key=$value"
    fi

    return 0
}

# show_full_config() - Display full configuration
show_full_config() {
    local config_file="$1"

    log_debug "Showing full configuration"

    # Load configuration
    config_load

    echo "Configuration file: $config_file"
    echo ""

    # Show all config values
    echo "=== Model Settings ==="
    echo "MODEL_CLARIFY=$(config_get MODEL_CLARIFY)"
    echo "MODEL_SPECS=$(config_get MODEL_SPECS)"
    echo "MODEL_ARCH=$(config_get MODEL_ARCH)"
    echo "MODEL_PLAN=$(config_get MODEL_PLAN)"
    echo "MODEL_BUILD_PRIMARY=$(config_get MODEL_BUILD_PRIMARY)"
    echo "MODEL_BUILD_SECONDARY=$(config_get MODEL_BUILD_SECONDARY)"
    echo "MODEL_GATE=$(config_get MODEL_GATE)"
    echo "MODEL_FEEDBACK=$(config_get MODEL_FEEDBACK)"
    echo ""

    echo "=== HITL Settings ==="
    echo "HITL_ENABLED=$(config_get HITL_ENABLED)"
    echo "HITL_MODE=$(config_get HITL_MODE)"
    echo "HITL_TIMEOUT=$(config_get HITL_TIMEOUT || echo '(none)')"
    echo ""

    echo "=== Build Settings ==="
    echo "BUILD_MAX_ITERATIONS=$(config_get BUILD_MAX_ITERATIONS)"
    echo "BUILD_BACKPRESSURE_TESTS=$(config_get BUILD_BACKPRESSURE_TESTS)"
    echo "BUILD_BACKPRESSURE_TYPECHECK=$(config_get BUILD_BACKPRESSURE_TYPECHECK)"
    echo "BUILD_BACKPRESSURE_LINT=$(config_get BUILD_BACKPRESSURE_LINT)"
    echo ""

    echo "=== Retry Settings ==="
    echo "RETRY_MAX_ATTEMPTS=$(config_get RETRY_MAX_ATTEMPTS)"
    echo "RETRY_BASE_DELAY=$(config_get RETRY_BASE_DELAY)"

    return 0
}

# show_help() - Display help message
show_help() {
    cat <<EOF
workflow config - Manage configuration

USAGE:
    workflow config [options]

DESCRIPTION:
    Manage workflow configuration settings.

    Configuration is stored in .workflow/config.sh and contains settings for
    model selection, HITL behavior, build options, and retry behavior.

OPTIONS:
    --edit              Open config file in \$EDITOR
    --get KEY           Get specific config value
    --set KEY=VALUE     Set config value (persists to file)
    --help, -h          Show this help message

EXAMPLES:
    # Show all configuration
    workflow config

    # Get specific value
    workflow config --get MODEL_BUILD_PRIMARY

    # Set a value
    workflow config --set MODEL_BUILD_PRIMARY=sonnet

    # Edit configuration interactively
    workflow config --edit

    # Enable HITL
    workflow config --set HITL_ENABLED=true
    workflow config --set HITL_MODE=milestone

CONFIGURATION KEYS:
    Model Settings:
        MODEL_CLARIFY, MODEL_SPECS, MODEL_ARCH, MODEL_PLAN,
        MODEL_BUILD_PRIMARY, MODEL_BUILD_SECONDARY, MODEL_GATE, MODEL_FEEDBACK

    HITL Settings:
        HITL_ENABLED, HITL_MODE, HITL_TIMEOUT

    Build Settings:
        BUILD_MAX_ITERATIONS, BUILD_BACKPRESSURE_TESTS,
        BUILD_BACKPRESSURE_TYPECHECK, BUILD_BACKPRESSURE_LINT

    Retry Settings:
        RETRY_MAX_ATTEMPTS, RETRY_BASE_DELAY

EXIT CODES:
    0    Success
    1    Error (invalid key, permission denied)

NOTES:
    - Valid model values: opus, sonnet, haiku
    - Valid HITL modes: task, milestone, uncertain, every:N
    - Environment variables (WORKFLOW_<KEY>) override config file values
    - Never store secrets in config files; use environment variables
EOF
}

# Main execution
main() {
    cmd_config "$@"
}

# Run main if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
