# Spec-to-Ship Workflow Configuration
# Generated by workflow config

# Provider Selection (claude, opencode, openai)
PROVIDER_DEFAULT="claude"
# PROVIDER_CLARIFY="claude"
# PROVIDER_SPECS="claude"
# PROVIDER_ARCH="claude"
# PROVIDER_PLAN="claude"
# PROVIDER_BUILD="claude"
# PROVIDER_GATE="claude"
# PROVIDER_FEEDBACK="claude"

# Provider-Specific Model Mappings
# Claude Models
PROVIDER_CLAUDE_MODEL_HIGH="claude-opus-4-20250514"
PROVIDER_CLAUDE_MODEL_MEDIUM="claude-sonnet-4-5-20250929"
PROVIDER_CLAUDE_MODEL_LOW="claude-haiku-4-20250319"

# OpenCode Models
PROVIDER_OPENCODE_MODEL_HIGH="opencode/grok-code"
PROVIDER_OPENCODE_MODEL_MEDIUM="opencode/gpt-5-nano"
PROVIDER_OPENCODE_MODEL_LOW="opencode/glm-4.7-free"

# Capability Requirements per Phase (high, medium, low)
# CAPABILITY_CLARIFY="high"
# CAPABILITY_SPECS="medium"
# CAPABILITY_ARCH="high"
# CAPABILITY_PLAN="high"
# CAPABILITY_BUILD="high"
# CAPABILITY_GATE="medium"
# CAPABILITY_FEEDBACK="low"

# Legacy Model Selection (backward compatibility)
MODEL_CLARIFY="opus"
MODEL_SPECS="sonnet"
MODEL_ARCH="opus"
MODEL_PLAN="opus"
MODEL_BUILD_PRIMARY="opus"
MODEL_BUILD_SECONDARY="sonnet"
MODEL_GATE="sonnet"
MODEL_FEEDBACK="haiku"

# Human-in-the-Loop (HITL) Settings
HITL_ENABLED="false"
HITL_MODE="milestone"  # task, milestone, uncertain, every:N
HITL_TIMEOUT=""        # e.g., "5m", "1h" (empty for no timeout)

# Build Settings
BUILD_MAX_ITERATIONS="0"            # 0 = unlimited
BUILD_BACKPRESSURE_TESTS="true"     # Run tests before commit
BUILD_BACKPRESSURE_TYPECHECK="false" # Run typecheck before commit
BUILD_BACKPRESSURE_LINT="true"      # Run lint before commit

# Retry Settings
RETRY_MAX_ATTEMPTS="3"
RETRY_BASE_DELAY="2"

# Notes:
# - Provider selection allows mixing different AI providers per phase
# - Capabilities map to provider-specific models automatically
# - Legacy model settings still work for backward compatibility
# - Secrets should be stored in environment variables (e.g., CLAUDE_API_KEY)
# - Use WORKFLOW_<KEY> environment variables to override these settings
# - Edit with: workflow config --edit
PROVIDER_BUILD="opencode"
